# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

# Network connection and parsing
  pod 'Alamofire', '~> 5.2'

# UI
  pod 'SDWebImage', '~> 5.0'
  pod 'ReadMoreTextView'
end
